M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 09:31:12 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T09:31:12-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.5Y-2.2
X5.5Y-2.5
X5.6Y-2.1
X5.6Y-2.5
X5.9Y-2.7
X6.1Y-2.3
X6.2Y-2.4
X6.6Y-2.4
X6.6Y-2.8
X7.0Y-2.8
T2
X6.7Y-1.9
X6.7Y-2.1
T0
M30
